### ISSUE TITLE
Lua module will be built each time

### ISSUE THREAD

**Issue by isaoshimizu** [chef-cookbooks/chef_nginx#86] opened 2017-03-22 08:34 UTC
### Cookbook version

5.1.2

### Chef-client version

12.19.36

### Platform Details

Ubuntu 14.04

### Scenario:

apply with ngx_lua_module

### Steps to Reproduce:

add attribute value `chef_nginx::ngx_lua_module` to `node['nginx']['source']['modules']`

### Expected Result:

It is not compiled when it is applied twice.

### Actual Result:

Even when applied twice it will be compiled every time.

**Comment by Sauraus** [comment] 2017-03-29 01:21
What do you mean by `It is not compiled when it is applied twice.`?

**Comment by isaoshimizu** [comment] 2017-04-04 09:04
If nginx and library apply the recipe again with the same version, the source code should be applied again without downloading and compiling.

**Comment by Sauraus** [comment] 2017-04-04 21:44
I can confirm, removing the `"` from the options prevents the lua library from being rebuilt each time.

**Comment by tas50** [comment] 2017-07-12 22:56
It looks like we can close this one out at this point. Feel free to open it up if you're still having the problem

**Closed by tas50** 2017-07-12 22:57 UTC
Labels: Type: Bug
