### ISSUE TITLE
nginx_site 'Disable default site' do error

### ISSUE THREAD

**Issue by funzoneq** [chef-cookbooks/chef_nginx#72] opened 2017-02-20 09:37 UTC
### Cookbook version
5.0.7

### Chef-client version
chef_12.18.31-1_amd64.deb

### Platform Details
Ubuntu 14.04

### Scenario:
I'm trying to disable the default nginx site.

### Steps to Reproduce:
```
# Nginx setttings
default['nginx']['default_site_enabled'] = false
```

### Expected Result:
I expect the default site will be removed.

### Actual Result:
```
==> default: ================================================================================
==> default:
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/lsw-oxidized/recipes/default.rb
==> default:
==> default: ================================================================================
==> default:
==> default:
==> default:
==> default:
==> default: ArgumentError
==> default:
==> default: -------------
==> default:   wrong number of arguments (given 1, expected 0)
==> default:
==> default:   Cookbook Trace:
==> default:   ---------------
==> default:     /var/chef/cache/cookbooks/chef_nginx/recipes/commons_conf.rb:36:in `block in from_file'
==> default:     /var/chef/cache/cookbooks/chef_nginx/recipes/commons_conf.rb:35:in `from_file'
==> default:     /var/chef/cache/cookbooks/chef_nginx/recipes/commons.rb:24:in `from_file'
==> default:     /var/chef/cache/cookbooks/chef_nginx/recipes/package.rb:53:in `from_file'
==> default:     /var/chef/cache/cookbooks/chef_nginx/recipes/default.rb:22:in `from_file'
==> default:     /var/chef/cache/cookbooks/lsw-oxidized/recipes/webserver.rb:2:in `from_file'
==> default:     /var/chef/cache/cookbooks/lsw-oxidized/recipes/default.rb:9:in `from_file'
==> default:
==> default:   Relevant File Content:
==> default:   ----------------------
==> default:   /var/chef/cache/cookbooks/chef_nginx/recipes/commons_conf.rb:
==> default:
==> default:    29:
==> default:    30:  template "#{node['nginx']['dir']}/sites-available/default" do
==> default:    31:    source 'default-site.erb'
==> default:    32:    notifies :reload, 'service[nginx]', :delayed
==> default:    33:  end
==> default:    34:
==> default:    35:  nginx_site 'Disable default site' do
==> default:    36>>   name 'default'
==> default:    37:    action node['nginx']['default_site_enabled'] ? :enable : :disable
==> default:    38:  end
==> default:    39:
```

**Comment by cheeseplus** [comment] 2017-02-22 19:12
What other cookbooks are in the run_list for this? Sounds like it could be something wrong with helpers not being in namespaces.

**Comment by e100** [comment] 2017-02-24 18:40
I ran across this exact same error when changing from the old nginx cookbook to chef_nginx cookbook.

One cookbook in my run_list depended on nginx while another depended on chef_nginx.
Changing all cookbooks to depend only on chef_nginx resolved the error.

**Comment by tas50** [comment] 2017-02-24 18:43
That sounds like a likely common thread here. Having both the custom resource and the existing definition loaded are going to cause some horrible failures.

**Comment by tas50** [comment] 2017-03-02 17:27
Closing this out since there's nothing we can do to avoid the problem. You'll need to get the old cookbook out of your runlist to avoid the collision.

**Closed** 2017-03-02 17:27 UTC

**Comment by rleibman** [comment] 2017-03-29 00:15
Avoiding the problem is super easy... please reopen, all you have to do is change the code to:
```
nginx_site 'default' do
  action node['nginx']['default_site_enabled'] ? :enable : :disable
end
```
i.e. remove the ugly 'Disable default site'

**Comment by rmoriz** [comment] 2017-04-27 15:55
I just ran into the same problem with 6.0.1 and chef-client 12.19.36.

duplicaty specification of name is a problem here.

fix is described by @rleibman

**Comment by rmoriz** [comment] 2017-04-27 16:01
Okay, it's worse. the `nginx` cookbook was neither in the run_list nor the Berksfile.lock but on the node in `/var/chef/cache/cookbooks/` - so it looks like chef is picking up definitions (aka old nginx_site) from cookbooks outside the run_list? weird.
